version: "3.8"
services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    ports:
      - "3000:80"  # Uygulama 3000 portunda çalışacak
    environment:
      - NODE_ENV=production
    volumes:
      - excalidraw-data:/app/data
volumes:
  excalidraw-data:
